# Player Commands
PLAY       cycle pause					# 再生/一時停止
PAUSE      cycle pause				# 再生/一時停止
PLAYPAUSE  cycle pause			# 再生/一時停止
KP0  cycle pause			# 再生/一時停止
FORWARD    frame-step				# 1コマ進む
REWIND     frame-back-step		# 1コマ戻る
NEXT       playlist-next					# 1ファイル進む
PREV       playlist-prev				# 1ファイル戻る

# Volume
- add volume -2
+ add volume 2

# Standard Commands
KP0       cycle pause					# 再生/一時停止
p      cycle pause ; show-text "${?pause==no:Play}${?pause==yes:Pause}"
					# 再生/一時停止（後ろの一文で再生時Play、一時停止時Pauseと表示が出る）
meta+w      quit							# 終了する
Ctrl+w      quit							# 終了する

KP8  cycle-values loop "inf" "no"		# 無限ループを切り替える
/ screenshot		# スクリーンショットを撮る
*          cycle fullscreen					# フルスクリーンにする

# OSD Infomation
i show-text "${filename}"              # osdにファイル名を表示する（Shift+iがファイル情報の表示に）
= show-text "${filename}"              # osdにファイル名を表示する（Shift+iがファイル情報の表示に）
tab show-text "${filename}"              # osdにファイル名を表示する（Shift+iがファイル情報の表示に）
Ctrl+p      show-text "${playlist}"
meta+p      show-text "${playlist}"

# Seek
LEFT        frame-back-step		# 1コマ戻る
KP1        frame-back-step		# 1コマ戻る
RIGHT       frame-step				# 1コマ進む
KP3       frame-step				# 1コマ進む
UP         playlist-prev				# 1ファイル進む
KP5         playlist-prev				# 1ファイル進む
DOWN         playlist-next			# 1ファイル進む
KP2         playlist-next			# 1ファイル進む
Shift+RIGHT no-osd seek  1 exact			# 1秒進む
KP6         no-osd seek  1 exact			# 1秒進む
Shift+LEFT  no-osd seek -1 exact			# 1秒戻る
KP4        no-osd seek -1 exact			# 1秒戻る
Shift+UP    no-osd seek  -30 exact			# 30秒戻る
KP7        no-osd seek  -30 exact			# 30秒戻る
Shift+DOWN  no-osd seek 30 exact		# 30秒進む
KP9        no-osd seek 30 exact		# 30秒進む

# Window Commands
f           cycle fullscreen					# フルスクリーンにする
Ctrl+SPACE  set fullscreen yes		# フルスクリーンをオンにする
Esc         set fullscreen no				# フルスクリーンをオフにする