player-operation-mode=pseudo-gui
log-file=~/Library/Logs/mpv.log

# fpsを動画に合わせる
correct-pts=yes
#再生が終わっても閉じない
keep-open=yes
#起動時自動再生しない(デフォルトがnoで自動再生される)
pause=yes
#起動時ループOFF(no)
loop=yes
#起動時から複数ファイル読み込んだ場合、プレイリストとしてループ
loop-playlist=inf
#スクリーンショットはpng、保存先指定（%fがファイル名、%Pがタイムコード）
screenshot-format=png
screenshot-template=~/Desktop/%f-%P
# On Screen Displayの設定
osd-bar=no